spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: create  # (1) 스키마 자동 생성
    show-sql: true      # (2) SQL 쿼리 출력
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        color-codes: true
        use_sql_comments: true
    defer-datasource-initialization: true  # 데이터소스 초기화 지연 설정. JPA의 초기화 설정을 마칠때까지 데이터소스 사용을 지연시킨다.
  #    open-in-view: true
  output:
    ansi:
      enabled: ALWAYS
  security:
    oauth2:
      client:
        registration:
          github: #localhost:8080/login/github
            redirect-uri: http://localhost:8080/login/oauth2/code/github
            client-id: 21d3161013611958e11d
            client-secret: d728d9f3e01f3079a8c69d9debbd15aac009f6b3
            scope:
              - "login"
              - "id"
              - "email"

logging:
  level:
    org:
      hibernate:
        #        SQL: debug           # jpa 설정에서 쿼리를 보여주므로 필요 없음.
        type:
          descriptor:
            sql:
              BasicBinder: trace
server:
  address: 0.0.0.0
  port: 8080 #포트 변경
  servlet:
    encoding:
      force-response: true

mail:
  address:
    admin: admin@gmail.com

jwt:
  key: ${JWT_SECRET_KEY}
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 420

